#!/bin/bash

echo "Executing CI on $(date)"

cd /home/nbird11/dev/Go/NbirdHttp

/usr/bin/git fetch
/usr/bin/git pull

# Check if any .go files were changed in the pull
if /usr/bin/git diff --name-only ORIG_HEAD HEAD | /usr/bin/grep -q "\.go$"; then
    echo "Restarting server..."
    /home/nbird11/dev/Go/NbirdHttp/restart
    echo "Running."
fi
